# Railway.app Configuration for Credit Card Fraud Detection System
# This file configures both API and Dashboard deployment

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables
[env]
ENVIRONMENT = "production"
PYTHONPATH = "/app"
PORT = "8000"

# Railway service configuration
[[services]]
name = "fraud-detection-api"
source = "."